# Generated by Django 5.2.7 on 2026-01-18 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='course_image')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('what_you_will_learn', models.TextField(blank=True)),
                ('course_price', models.DecimalField(blank=True, decimal_places=2, default=400.0, max_digits=8, null=True)),
                ('course_duration', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_type', models.CharField(choices=[('premium', 'Premium'), ('sort_term', 'Sort_Term'), ('professional', 'Professional'), ('free', 'Free')], default='premium', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Addmissionform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andman & Nicobar Island', 'Andman & Nicobar Island'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Hryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kasmir', 'Jammu & Kasmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerla', 'Kerla'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalay', 'Meghalay'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajsthan', 'Rajsthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=25)),
                ('pin', models.PositiveIntegerField()),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('board1', models.CharField(blank=True, max_length=100, null=True)),
                ('board2', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.PositiveBigIntegerField(blank=True, null=True)),
                ('passing_year1', models.PositiveBigIntegerField(blank=True, null=True)),
                ('passing_year2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage1', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage2', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('roll_number1', models.PositiveBigIntegerField(blank=True, null=True)),
                ('roll_number2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='photoimage')),
                ('signature', models.ImageField(blank=True, upload_to='signatureimage')),
                ('matriculation', models.FileField(blank=True, upload_to='matricdoc')),
                ('intermediate', models.FileField(blank=True, upload_to='intermediatedoc')),
                ('graducation', models.FileField(blank=True, upload_to='graducationdoc')),
                ('postgraducation', models.FileField(blank=True, upload_to='postgraducationdoc')),
                ('address_proof', models.FileField(blank=True, upload_to='photodoc')),
                ('course_applied_for', models.CharField(choices=[('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th,', '10th'), ('11th', '11th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Special Classes', 'Special Clases'), ('DCA', 'DCA'), ('CFA', 'CFA'), ('DDTP', 'DDTP'), ('DCAD', 'DCAD'), ('ADCA', 'ADCA'), ('DCP', 'DCP'), ('HDCA', 'HDCA'), ('DAP', 'DAP'), ('HDAP', 'HDAP'), ('HDIT', 'HDIT'), ('ADIT', 'ADIT'), ('DCH', 'DCH'), ('ADCHN', 'ADCHN'), ('DCN', 'DWD'), ('DWD', 'DWD'), ('DMM', 'DMM'), ('ADGA', 'ADGA'), ('DCT', 'DCT'), ('DOM', 'DOM'), ('DMR', 'DMR'), ('DID', 'DID'), ('Professional Courses', 'Professional Courses')], max_length=25)),
                ('registration_number', models.CharField(max_length=20, null=True, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.coursedisplay')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentid', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admission_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateTimeField(auto_now=True)),
                ('admission_status', models.CharField(choices=[('Payment_Not_Completed', 'Payment_Not_completed'), ('Accepted', 'Accepted'), ('Succsess', 'Succsess'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('admission_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.addmissionform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reg_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.payment')),
            ],
        ),
    ]
