# Generated by Django 5.0.7 on 2025-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmissionform',
            name='registration_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
